spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ejb:
          interceptor: com.openlab.gestiondestock.interceptor.Interceptor
      dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081


## logging Configuration ##
# Spécifier le fichier externe ou les messages sont stockés
logging:
  file:
      name: D:/OPENLAB/spring_log_file-api.log
  # Spécifier la taille maximale du fichier de journalisation

  logback:
     rollingpolicy:
         max-file-size: 100KB
  # spécifier le niveau de Log
  level:
      root: INFO
  # Spécifier la forme du message

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{36} - %msg%n








flickr:
  apiKey: f693090e4af3e6a6b02f2f72db4a99ad
  apiSecret: 43a29f27a19f02fd
  appKey: 72157720877443090-98c9a80a3be51c97
  appSecret: 2dbafb66bd9b1cd1
